import { lazy } from 'react'

export const LandingPage = lazy(() => import('@/pages/landing'))
export const LoginPage = lazy(() => import('@/pages/auth/login'))
export const RegisterPage = lazy(() => import('@/pages/auth/register'))
export const ForgotPasswordPage = lazy(() => import('@/pages/auth/forgot-password'))
export const ResetPasswordPage = lazy(() => import('@/pages/auth/reset-password'))
export const ChangePasswordPage = lazy(() => import('@/pages/auth/change-password'))
export const NotFoundPage = lazy(() => import('@/pages/errors/not-found'))
export const ServerErrorPage = lazy(() => import('@/pages/errors/server-error'))
export const UnauthorizedPage = lazy(() => import('@/pages/errors/unauthorized'))
export const OfflinePage = lazy(() => import('@/pages/errors/offline'))
export const SettingsPage = lazy(() => import('@/pages/settings'))
export const StudentHomePage = lazy(() => import('@/pages/student/home'))
export const StudentAssignmentsPage = lazy(() => import('@/pages/student/assignments'))
export const TeacherHomePage = lazy(() => import('@/pages/teacher/home'))
export const TeacherReviewsPage = lazy(() => import('@/pages/teacher/reviews'))
export const AdminHomePage = lazy(() => import('@/pages/admin/home'))
export const AdminUsersPage = lazy(() => import('@/pages/admin/users'))
export const AdminSystemPage = lazy(() => import('@/pages/admin/system'))
export const SuperAdminHomePage = lazy(() => import('@/pages/super-admin/home'))
export const SuperAdminPlaceholderPage = lazy(() => import('@/pages/super-admin/placeholder'))
export const PortalPlaceholder = lazy(() =>
  import('@/pages/_shared/portal-placeholder').then((m) => ({ default: m.PortalPlaceholder }))
)
export const CoursesListPage = lazy(() => import('@/pages/courses/courses-list'))
export const CourseCreatePage = lazy(() => import('@/pages/courses/course-create'))
export const CourseEditPage = lazy(() => import('@/pages/courses/course-edit'))
export const CourseDetailsPage = lazy(() => import('@/pages/courses/course-details'))
export const CategoriesListPage = lazy(() => import('@/pages/categories/categories-list'))
export const CategoryCreatePage = lazy(() => import('@/pages/categories/category-form'))
export const CategoryEditPage = lazy(() =>
  import('@/pages/categories/category-form').then((m) => ({ default: m.CategoryEditPage }))
)
export const BatchesListPage = lazy(() => import('@/pages/batches/batches-list'))
export const CurriculumBuilderPage = lazy(() => import('@/pages/curriculum/curriculum-builder'))
export const LessonEditPage = lazy(() => import('@/pages/curriculum/lesson-edit'))
export const LessonViewPage = lazy(() => import('@/pages/curriculum/lesson-view'))
export const StudentLearnPage = lazy(() => import('@/pages/curriculum/student-learn'))
export const PracticeQuestionsListPage = lazy(() => import('@/pages/practice/questions-list'))
export const PracticeQuestionFormPage = lazy(() => import('@/pages/practice/question-form'))
export const PracticeAnalyticsPage = lazy(() => import('@/pages/practice/analytics'))
export const PracticePreviewPage = lazy(() =>
  import('@/pages/practice/solve').then((m) => ({ default: m.PracticePreviewPage }))
)
export const StudentPracticeHomePage = lazy(() => import('@/pages/practice/student-home'))
export const StudentQuestionPage = lazy(() =>
  import('@/pages/practice/student-home').then((m) => ({ default: m.StudentQuestionPage }))
)
export const AssignmentsListPage = lazy(() => import('@/pages/assignments/assignments-list'))
export const AssignmentFormPage = lazy(() => import('@/pages/assignments/assignment-form'))
export const AssignmentAnalyticsPage = lazy(() => import('@/pages/assignments/analytics'))
export const StudentAssignmentDetailPage = lazy(() => import('@/pages/assignments/student-detail'))
export const AssignmentSubmissionsPage = lazy(() => import('@/pages/assignments/teacher-review'))
export const TeacherReviewPage = lazy(() =>
  import('@/pages/assignments/teacher-review').then((m) => ({ default: m.TeacherReviewPage }))
)
export const QuizzesListPage = lazy(() => import('@/pages/quizzes/quizzes-list'))
export const QuizFormPage = lazy(() => import('@/pages/quizzes/quiz-form'))
export const QuizAnalyticsPage = lazy(() => import('@/pages/quizzes/analytics'))
export const StudentQuizzesPage = lazy(() => import('@/pages/student/quizzes'))
export const StudentQuizDetailPage = lazy(() => import('@/pages/quizzes/take-quiz'))
export const QuizAttemptPage = lazy(() =>
  import('@/pages/quizzes/take-quiz').then((m) => ({ default: m.QuizAttemptPage }))
)
export const QuizAttemptsPage = lazy(() => import('@/pages/quizzes/attempts'))
export const QuizDetailHubPage = lazy(() =>
  import('@/pages/quizzes/attempts').then((m) => ({ default: m.QuizDetailHubPage }))
)
export const QuizPoolPage = lazy(() => import('@/pages/quizzes/pool'))
export const EnrollmentsListPage = lazy(() => import('@/pages/enrollment/enrollments-list'))
export const EnrollmentFormPage = lazy(() => import('@/pages/enrollment/enrollment-form'))
export const EnrollmentDetailPage = lazy(() => import('@/pages/enrollment/enrollment-detail'))
export const EnrollmentAnalyticsPage = lazy(() => import('@/pages/enrollment/analytics'))
export const StudentEnrollmentsPage = lazy(() => import('@/pages/enrollment/student-home'))
export const StudentProfilePage = lazy(() =>
  import('@/pages/enrollment/student-home').then((m) => ({ default: m.StudentProfilePage }))
)
export const BatchDetailPage = lazy(() => import('@/pages/batches/batch-detail'))
export const LiveClassesListPage = lazy(() => import('@/pages/live/classes-list'))
export const StudentClassesPage = lazy(() =>
  import('@/pages/live/classes-list').then((m) => ({ default: m.StudentClassesPage }))
)
export const LiveClassFormPage = lazy(() => import('@/pages/live/class-form'))
export const LiveClassDetailPage = lazy(() =>
  import('@/pages/live/class-form').then((m) => ({ default: m.LiveClassDetailPage }))
)
export const ClassAttendancePage = lazy(() => import('@/pages/live/attendance'))
export const StudentAttendancePage = lazy(() =>
  import('@/pages/live/attendance').then((m) => ({ default: m.StudentAttendancePage }))
)
export const AcademicCalendarPage = lazy(() => import('@/pages/live/calendar'))
export const AnnouncementsListPage = lazy(() => import('@/pages/live/announcements'))
export const AnnouncementFormPage = lazy(() =>
  import('@/pages/live/announcements').then((m) => ({ default: m.AnnouncementFormPage }))
)
export const AnnouncementDetailPage = lazy(() =>
  import('@/pages/live/announcements').then((m) => ({ default: m.AnnouncementDetailPage }))
)
export const LiveAdminDashboardPage = lazy(() => import('@/pages/live/admin-dashboard'))
export const CertificateVerifyPage = lazy(() => import('@/pages/certificates/verify'))
export const CertificatesListPage = lazy(() => import('@/pages/certificates/list'))
export const CertificateDetailPage = lazy(() => import('@/pages/certificates/detail'))
export const CertificateTemplatesPage = lazy(() => import('@/pages/certificates/templates'))
export const CertificateRulesPage = lazy(() => import('@/pages/certificates/rules'))
export const StudentPortfolioPage = lazy(() => import('@/pages/certificates/portfolio'))
export const PublicPortfolioPage = lazy(() =>
  import('@/pages/certificates/portfolio').then((m) => ({ default: m.PublicPortfolioPage }))
)
export const LeaderboardPage = lazy(() => import('@/pages/certificates/leaderboard'))
export const GamificationAdminPage = lazy(() => import('@/pages/certificates/admin-dashboard'))
export const TeacherCertificatesPage = lazy(() =>
  import('@/pages/certificates/admin-dashboard').then((m) => ({ default: m.TeacherCertificatesPage }))
)
export const FinanceDashboardPage = lazy(() => import('@/pages/finance/dashboard'))
export const AdmissionsPage = lazy(() => import('@/pages/finance/admissions'))
export const FeePlansPage = lazy(() => import('@/pages/finance/fee-plans'))
export const StudentFeesPage = lazy(() => import('@/pages/finance/student-fees'))
export const FeeAccountDetailPage = lazy(() =>
  import('@/pages/finance/student-fees').then((m) => ({ default: m.FeeAccountDetailPage }))
)
export const ReceiptDetailPage = lazy(() =>
  import('@/pages/finance/student-fees').then((m) => ({ default: m.ReceiptDetailPage }))
)
export const ReceiptVerifyPage = lazy(() =>
  import('@/pages/finance/student-fees').then((m) => ({ default: m.ReceiptVerifyPage }))
)
export const ExpensesPage = lazy(() => import('@/pages/finance/expenses-reports'))
export const FinanceReportsPage = lazy(() =>
  import('@/pages/finance/expenses-reports').then((m) => ({ default: m.FinanceReportsPage }))
)
export const TeacherFeeStatusPage = lazy(() =>
  import('@/pages/finance/expenses-reports').then((m) => ({ default: m.TeacherFeeStatusPage }))
)
export const MessagesPage = lazy(() => import('@/pages/communication/messages'))
export const ForumsPage = lazy(() => import('@/pages/communication/forums'))
export const ForumThreadPage = lazy(() =>
  import('@/pages/communication/forums').then((m) => ({ default: m.ForumThreadPage }))
)
export const HelpdeskPage = lazy(() => import('@/pages/communication/helpdesk'))
export const TicketDetailPage = lazy(() =>
  import('@/pages/communication/helpdesk').then((m) => ({ default: m.TicketDetailPage }))
)
export const CrmPage = lazy(() => import('@/pages/communication/crm'))
export const CareerPortalPage = lazy(() => import('@/pages/communication/career'))
export const JobDetailPage = lazy(() =>
  import('@/pages/communication/career').then((m) => ({ default: m.JobDetailPage }))
)
export const CareerAdminPage = lazy(() =>
  import('@/pages/communication/career').then((m) => ({ default: m.CareerAdminPage }))
)
export const SurveysPage = lazy(() =>
  import('@/pages/communication/career').then((m) => ({ default: m.SurveysPage }))
)
export const SurveyTakePage = lazy(() =>
  import('@/pages/communication/career').then((m) => ({ default: m.SurveyTakePage }))
)
export const AlumniPage = lazy(() =>
  import('@/pages/communication/career').then((m) => ({ default: m.AlumniPage }))
)
