const { WORKSPACE_TYPES, WORKSPACE_TYPE_META, getWorkspaceTypeMeta } = require('./workspace-types')

module.exports = {
  APP_NAME: 'CodeCrafters Learning Platform',
  API_VERSION: 'v1',
  WORKSPACE_TYPES,
  WORKSPACE_TYPE_META,
  getWorkspaceTypeMeta,
  ROLES: Object.freeze({
    SUPER_ADMIN: 'super_admin',
    ADMIN: 'admin',
    TEACHER: 'teacher',
    STUDENT: 'student',
  }),
  USER_STATUS: Object.freeze({
    ACTIVE: 'active',
    INACTIVE: 'inactive',
    SUSPENDED: 'suspended',
  }),
  ROLE_HIERARCHY: Object.freeze({
    super_admin: ['super_admin', 'admin', 'teacher', 'student'],
    admin: ['admin', 'teacher', 'student'],
    teacher: ['teacher'],
    student: ['student'],
  }),
  COURSE_STATUS: Object.freeze({
    DRAFT: 'draft',
    PUBLISHED: 'published',
    ARCHIVED: 'archived',
  }),
  COURSE_DIFFICULTY: Object.freeze({
    BEGINNER: 'beginner',
    INTERMEDIATE: 'intermediate',
    ADVANCED: 'advanced',
  }),
  COURSE_VISIBILITY: Object.freeze({
    PUBLIC: 'public',
    PRIVATE: 'private',
    PASSWORD: 'password_protected',
  }),
  BATCH_STATUS: Object.freeze({
    UPCOMING: 'upcoming',
    ACTIVE: 'active',
    COMPLETED: 'completed',
    CANCELLED: 'cancelled',
    ARCHIVED: 'archived',
  }),
  BATCH_DAYS: Object.freeze([
    'monday',
    'tuesday',
    'wednesday',
    'thursday',
    'friday',
    'saturday',
    'sunday',
  ]),
  CATEGORY_STATUS: Object.freeze({
    ACTIVE: 'active',
    INACTIVE: 'inactive',
  }),
  CURRICULUM_STATUS: Object.freeze({
    DRAFT: 'draft',
    PUBLISHED: 'published',
    ARCHIVED: 'archived',
  }),
  LESSON_TYPES: Object.freeze({
    TEXT: 'text',
    MARKDOWN: 'markdown',
    VIDEO: 'video',
    CODE: 'code_example',
    GALLERY: 'image_gallery',
    LINK: 'external_link',
    PDF: 'pdf',
    DOWNLOAD: 'download',
    ARTICLE: 'article',
  }),
  RESOURCE_TYPES: Object.freeze({
    PDF: 'pdf',
    ZIP: 'zip',
    GITHUB: 'github',
    DOCS: 'documentation',
    WEBSITE: 'website',
    SOURCE: 'source_code',
    CHEATSHEET: 'cheat_sheet',
    DOWNLOAD: 'downloadable',
    VIDEO: 'external_video',
  }),
  RESOURCE_VISIBILITY: Object.freeze({
    PUBLIC: 'public',
    ENROLLED: 'enrolled',
    PREVIEW: 'preview',
  }),
}
