/**
 * Lesson Workspace Types — drive UI layout and available panels.
 * Add new types here; UI reads capabilities from this registry.
 */
const WORKSPACE_TYPES = Object.freeze({
  THEORY: 'theory',
  THEORY_PRACTICE: 'theory_practice',
  CODING_CHALLENGE: 'coding_challenge',
  MINI_PROJECT: 'mini_project',
  ASSIGNMENT: 'assignment',
  QUIZ: 'quiz',
  VIDEO: 'video_lesson',
  READING: 'reading_only',
  DOWNLOADABLE: 'downloadable_resource',
})

const WORKSPACE_TYPE_META = Object.freeze({
  [WORKSPACE_TYPES.THEORY]: {
    label: 'Theory',
    description: 'Lesson content only — no live coding.',
    showEditor: false,
    showPreview: false,
    showConsole: false,
    showTests: false,
    showDiscussion: true,
    showResources: true,
    showVideo: false,
    showQuiz: false,
    showAssignment: false,
    showAi: true,
  },
  [WORKSPACE_TYPES.THEORY_PRACTICE]: {
    label: 'Theory + Practice',
    description: 'Read the lesson and practice in the live workspace.',
    showEditor: true,
    showPreview: true,
    showConsole: true,
    showTests: false,
    showDiscussion: true,
    showResources: true,
    showVideo: false,
    showQuiz: false,
    showAssignment: false,
    showAi: true,
  },
  [WORKSPACE_TYPES.CODING_CHALLENGE]: {
    label: 'Coding Challenge',
    description: 'Challenge with tests, hints, and evaluation.',
    showEditor: true,
    showPreview: true,
    showConsole: true,
    showTests: true,
    showDiscussion: true,
    showResources: false,
    showVideo: false,
    showQuiz: false,
    showAssignment: false,
    showAi: true,
  },
  [WORKSPACE_TYPES.MINI_PROJECT]: {
    label: 'Mini Project',
    description: 'Multi-file project workspace.',
    showEditor: true,
    showPreview: true,
    showConsole: true,
    showTests: true,
    showDiscussion: true,
    showResources: true,
    showVideo: false,
    showQuiz: false,
    showAssignment: false,
    showAi: true,
  },
  [WORKSPACE_TYPES.ASSIGNMENT]: {
    label: 'Assignment',
    description: 'Graded assignment submission (Prompt 007+).',
    showEditor: true,
    showPreview: true,
    showConsole: true,
    showTests: true,
    showDiscussion: false,
    showResources: true,
    showVideo: false,
    showQuiz: false,
    showAssignment: true,
    showAi: true,
  },
  [WORKSPACE_TYPES.QUIZ]: {
    label: 'Quiz',
    description: 'Quiz engine surface (Prompt 007+).',
    showEditor: false,
    showPreview: false,
    showConsole: false,
    showTests: false,
    showDiscussion: false,
    showResources: false,
    showVideo: false,
    showQuiz: true,
    showAssignment: false,
    showAi: true,
  },
  [WORKSPACE_TYPES.VIDEO]: {
    label: 'Video Lesson',
    description: 'Primary video player with notes.',
    showEditor: false,
    showPreview: false,
    showConsole: false,
    showTests: false,
    showDiscussion: true,
    showResources: true,
    showVideo: true,
    showQuiz: false,
    showAssignment: false,
    showAi: true,
  },
  [WORKSPACE_TYPES.READING]: {
    label: 'Reading Only',
    description: 'Focused reading — no coding lab.',
    showEditor: false,
    showPreview: false,
    showConsole: false,
    showTests: false,
    showDiscussion: true,
    showResources: true,
    showVideo: false,
    showQuiz: false,
    showAssignment: false,
    showAi: false,
  },
  [WORKSPACE_TYPES.DOWNLOADABLE]: {
    label: 'Downloadable Resource',
    description: 'Resource-first lesson surface.',
    showEditor: false,
    showPreview: false,
    showConsole: false,
    showTests: false,
    showDiscussion: false,
    showResources: true,
    showVideo: false,
    showQuiz: false,
    showAssignment: false,
    showAi: false,
  },
})

function getWorkspaceTypeMeta(type) {
  return WORKSPACE_TYPE_META[type] || WORKSPACE_TYPE_META[WORKSPACE_TYPES.THEORY]
}

module.exports = {
  WORKSPACE_TYPES,
  WORKSPACE_TYPE_META,
  getWorkspaceTypeMeta,
}
