import {
  LayoutDashboard,
  BookOpen,
  ClipboardList,
  Users,
  Shield,
  Settings,
  BarChart3,
  GraduationCap,
  FolderTree,
  Layers3,
  Code2,
  ListChecks,
  UserRound,
  Video,
  Megaphone,
  CalendarDays,
} from 'lucide-react'
import { ROLES, ROUTES } from '@/constants'

export const NAV_BY_ROLE = {
  [ROLES.SUPER_ADMIN]: [
    { to: ROUTES.SUPER_ADMIN, label: 'Overview', icon: LayoutDashboard, end: true },
    { to: `${ROUTES.SUPER_ADMIN}/users`, label: 'All Users', icon: Users },
    { to: `${ROUTES.SUPER_ADMIN}/admins`, label: 'Admins', icon: Shield },
    { to: `${ROUTES.SUPER_ADMIN}/courses`, label: 'Courses', icon: BookOpen },
    { to: `${ROUTES.SUPER_ADMIN}/enrollments`, label: 'Enrollments', icon: UserRound },
    { to: `${ROUTES.SUPER_ADMIN}/classes`, label: 'Live Classes', icon: Video },
    { to: `${ROUTES.SUPER_ADMIN}/calendar`, label: 'Calendar', icon: CalendarDays },
    { to: `${ROUTES.SUPER_ADMIN}/announcements`, label: 'Announcements', icon: Megaphone },
    { to: `${ROUTES.SUPER_ADMIN}/practice`, label: 'Practice', icon: Code2 },
    { to: `${ROUTES.SUPER_ADMIN}/assignments`, label: 'Assignments', icon: ClipboardList },
    { to: `${ROUTES.SUPER_ADMIN}/quizzes`, label: 'Quizzes', icon: ListChecks },
    { to: `${ROUTES.SUPER_ADMIN}/categories`, label: 'Categories', icon: FolderTree },
    { to: `${ROUTES.SUPER_ADMIN}/batches`, label: 'Batches', icon: Layers3 },
    { to: `${ROUTES.SUPER_ADMIN}/reports`, label: 'Reports', icon: BarChart3 },
    { to: `${ROUTES.SUPER_ADMIN}/system`, label: 'System', icon: Settings },
  ],
  [ROLES.ADMIN]: [
    { to: ROUTES.ADMIN, label: 'Overview', icon: LayoutDashboard, end: true },
    { to: `${ROUTES.ADMIN}/users`, label: 'Users', icon: Users },
    { to: `${ROUTES.ADMIN}/teachers`, label: 'Teachers', icon: GraduationCap },
    { to: `${ROUTES.ADMIN}/courses`, label: 'Courses', icon: BookOpen },
    { to: `${ROUTES.ADMIN}/enrollments`, label: 'Enrollments', icon: UserRound },
    { to: `${ROUTES.ADMIN}/classes`, label: 'Live Classes', icon: Video },
    { to: `${ROUTES.ADMIN}/calendar`, label: 'Calendar', icon: CalendarDays },
    { to: `${ROUTES.ADMIN}/announcements`, label: 'Announcements', icon: Megaphone },
    { to: `${ROUTES.ADMIN}/practice`, label: 'Practice', icon: Code2 },
    { to: `${ROUTES.ADMIN}/assignments`, label: 'Assignments', icon: ClipboardList },
    { to: `${ROUTES.ADMIN}/quizzes`, label: 'Quizzes', icon: ListChecks },
    { to: `${ROUTES.ADMIN}/categories`, label: 'Categories', icon: FolderTree },
    { to: `${ROUTES.ADMIN}/batches`, label: 'Batches', icon: Layers3 },
    { to: `${ROUTES.ADMIN}/system`, label: 'System', icon: Shield },
  ],
  [ROLES.TEACHER]: [
    { to: ROUTES.TEACHER, label: 'Overview', icon: LayoutDashboard, end: true },
    { to: `${ROUTES.TEACHER}/classes`, label: 'Live Classes', icon: Video },
    { to: `${ROUTES.TEACHER}/calendar`, label: 'Calendar', icon: CalendarDays },
    { to: `${ROUTES.TEACHER}/announcements`, label: 'Announcements', icon: Megaphone },
    { to: `${ROUTES.TEACHER}/batches`, label: 'Batches', icon: Layers3 },
    { to: `${ROUTES.TEACHER}/enrollments`, label: 'Enrollments', icon: UserRound },
    { to: `${ROUTES.TEACHER}/reviews`, label: 'Reviews', icon: ClipboardList },
    { to: `${ROUTES.TEACHER}/courses`, label: 'Courses', icon: BookOpen },
    { to: `${ROUTES.TEACHER}/practice`, label: 'Practice', icon: Code2 },
    { to: `${ROUTES.TEACHER}/assignments`, label: 'Assignments', icon: ClipboardList },
    { to: `${ROUTES.TEACHER}/quizzes`, label: 'Quizzes', icon: ListChecks },
  ],
  [ROLES.STUDENT]: [
    { to: ROUTES.STUDENT, label: 'Overview', icon: LayoutDashboard, end: true },
    { to: `${ROUTES.STUDENT}/courses`, label: 'Courses', icon: BookOpen },
    { to: `${ROUTES.STUDENT}/classes`, label: 'Live Classes', icon: Video },
    { to: `${ROUTES.STUDENT}/calendar`, label: 'Calendar', icon: CalendarDays },
    { to: `${ROUTES.STUDENT}/attendance`, label: 'Attendance', icon: ClipboardList },
    { to: `${ROUTES.STUDENT}/announcements`, label: 'Announcements', icon: Megaphone },
    { to: `${ROUTES.STUDENT}/profile`, label: 'Profile', icon: UserRound },
    { to: `${ROUTES.STUDENT}/practice`, label: 'Practice', icon: Code2 },
    { to: `${ROUTES.STUDENT}/assignments`, label: 'Assignments', icon: ClipboardList },
    { to: `${ROUTES.STUDENT}/quizzes`, label: 'Quizzes', icon: ListChecks },
  ],
}

export function getNavForRole(role) {
  return NAV_BY_ROLE[role] || NAV_BY_ROLE[ROLES.STUDENT]
}
