const express = require('express')
const { getHealth } = require('../../controllers/health.controller')
const authRoutes = require('./auth.routes')
const categoryRoutes = require('./category.routes')
const courseRoutes = require('./course.routes')
const batchRoutes = require('./batch.routes')
const usersRoutes = require('./users.routes')
const moduleRoutes = require('./module.routes')
const weekRoutes = require('./week.routes')
const topicRoutes = require('./topic.routes')
const lessonRoutes = require('./lesson.routes')
const resourceRoutes = require('./resource.routes')
const curriculumRoutes = require('./curriculum.routes')

const router = express.Router()

router.get('/health', getHealth)
router.use('/auth', authRoutes)
router.use('/categories', categoryRoutes)
router.use('/courses', courseRoutes)
router.use('/courses/:courseId/curriculum', curriculumRoutes)
router.use('/batches', batchRoutes)
router.use('/users', usersRoutes)
router.use('/modules', moduleRoutes)
router.use('/weeks', weekRoutes)
router.use('/topics', topicRoutes)
router.use('/lessons', lessonRoutes)
router.use('/resources', resourceRoutes)
router.use('/learning', require('./learning.routes'))

module.exports = router
